In [1]:
%pip install tensorflow==2.15.0 keras==2.15.0

Collecting tensorflow==2.15.0
  Using cached tensorflow-2.15.0-cp39-cp39-win_amd64.whl (2.1 kB)
Collecting keras==2.15.0
  Downloading keras-2.15.0-py3-none-any.whl (1.7 MB)
Collecting tensorflow-intel==2.15.0; platform_system == "Windows"
  Downloading tensorflow_intel-2.15.0-cp39-cp39-win_amd64.whl (300.8 MB)
Collecting wrapt<1.15,>=1.11.0
  Downloading wrapt-1.14.2-cp39-cp39-win_amd64.whl (35 kB)
Collecting tensorflow-io-gcs-filesystem>=0.23.1
  Downloading tensorflow_io_gcs_filesystem-0.31.0-cp39-cp39-win_amd64.whl (1.5 MB)
Collecting ml-dtypes~=0.2.0
  Downloading ml_dtypes-0.2.0-cp39-cp39-win_amd64.whl (938 kB)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (0.7.0)
Requirement already satisfied: libclang>=13.0.0 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (18.1.1)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3
  Downloading protobuf-4.25.8-cp39-cp39-win_amd64.whl (413 kB)
Collecting tensorboard<2.16,>=2.15
  Downloading tensorboard-2.15.2-py3-none-any.whl (5.5 MB)
Requirement already satisfied: termcolor>=1.1.0 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (3.1.0)
Requirement already satisfied: setuptools in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (49.2.1)
Requirement already satisfied: flatbuffers>=23.5.26 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (25.12.19)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (1.78.0)
Requirement already satisfied: packaging in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (26.0)
Requirement already satisfied: typing-extensions>=3.6.6 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (4.15.0)
Requirement already satisfied: opt-einsum>=2.3.2 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (3.4.0)
Requirement already satisfied: google-pasta>=0.1.1 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (0.2.0)
Requirement already satisfied: absl-py>=1.0.0 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (2.3.1)
Requirement already satisfied: six>=1.12.0 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (1.17.0)
Requirement already satisfied: astunparse>=1.6.0 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (1.6.3)
Requirement already satisfied: h5py>=2.9.0 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (3.14.0)
Collecting tensorflow-estimator<2.16,>=2.15.0
  Downloading tensorflow_estimator-2.15.0-py2.py3-none-any.whl (441 kB)
Collecting numpy<2.0.0,>=1.23.5
  Downloading numpy-1.26.4-cp39-cp39-win_amd64.whl (15.8 MB)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (3.1.6)
Collecting google-auth-oauthlib<2,>=0.5
  Downloading google_auth_oauthlib-1.3.0-py3-none-any.whl (19 kB)
Requirement already satisfied: markdown>=2.6.8 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (3.9)
Collecting google-auth<3,>=1.6.3
  Downloading google_auth-2.48.0-py3-none-any.whl (236 kB)
Requirement already satisfied: requests<3,>=2.21.0 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (2.32.5)
Requirement already satisfied: wheel<1.0,>=0.23.0 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (0.46.3)
Requirement already satisfied: markupsafe>=2.1.1 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (3.0.3)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Requirement already satisfied: importlib-metadata>=4.4; python_version < "3.10" in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from markdown>=2.6.8->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (8.7.1)
Collecting cryptography>=38.0.3
  Downloading cryptography-43.0.3-cp39-abi3-win_amd64.whl (3.1 MB)
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.9.1-py3-none-any.whl (34 kB)
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Requirement already satisfied: idna<4,>=2.5 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (2026.2.25)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (3.4.4)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.3.1-py3-none-any.whl (160 kB)
Requirement already satisfied: zipp>=3.20 in d:\ai-mltraining\machine_learning\venv\lib\site-packages (from importlib-metadata>=4.4; python_version < "3.10"->markdown>=2.6.8->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0; platform_system == "Windows"->tensorflow==2.15.0) (3.23.0)
Collecting cffi>=1.12; platform_python_implementation != "PyPy"
  Downloading cffi-2.0.0-cp39-cp39-win_amd64.whl (182 kB)
Collecting pyasn1>=0.1.3
  Downloading pyasn1-0.6.2-py3-none-any.whl (83 kB)
Collecting pycparser; implementation_name != "PyPy"
  Downloading pycparser-2.23-py3-none-any.whl (118 kB)
Installing collected packages: wrapt, tensorflow-io-gcs-filesystem, numpy, ml-dtypes, keras, protobuf, oauthlib, requests-oauthlib, pycparser, cffi, cryptography, pyasn1, rsa, pyasn1-modules, google-auth, google-auth-oauthlib, tensorboard, tensorflow-estimator, tensorflow-intel, tensorflow
  Attempting uninstall: wrapt
    Found existing installation: wrapt 2.1.1
    Uninstalling wrapt-2.1.1:
      Successfully uninstalled wrapt-2.1.1
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'D:\\AI-MLTraining\\machine_learning\\venv\\Lib\\site-packages\\~umpy.libs\\libscipy_openblas64_-caad452230ae4ddb57899b8b3a33c55c.dll'
Consider using the `--user` option or check the permissions.

WARNING: You are using pip version 20.2.3; however, version 26.0.1 is available.
You should consider upgrading via the 'd:\AI-MLTraining\machine_learning\venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [1]:
import tensorflow as tf
from tensorflow import keras

print(f"TensorFlow Version: {tf.__version__}")
print(f"Keras Version: {keras.__version__}")

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
import numpy as np
import pandas as pd
import tensorflow

ModuleNotFoundError: No module named 'tensorflow'

In [4]:
import sys
print(sys.executable)

d:\AI-MLTraining\machine_learning\venv\Scripts\python.exe

In [2]:
print(tensorflow.__version__)

NameError: name 'tensorflow' is not defined

In [2]:
df=pd.read_csv("Churn_Modelling.csv")

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df.shape

(10000, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [8]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [9]:
df.drop(columns=['RowNumber', 'CustomerId', 'Surname'],inplace=True)

In [10]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [11]:
print(df.columns)

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

In [12]:
df=pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True, dtype=int)

In [13]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0,0

In [14]:
X = df.drop(columns=['Exited'])
y = df['Exited']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [15]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0

In [16]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [18]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [21]:
pip cache purge

Files removed: 15
Note: you may need to restart the kernel to use updated packages.

In [20]:
pip list

Package                 Version
----------------------- -----------
absl-py                 2.3.1
asttokens               3.0.1
astunparse              1.6.3
certifi                 2026.2.25
charset-normalizer      3.4.4
colorama                0.4.6
comm                    0.2.3
contourpy               1.3.0
cycler                  0.12.1
debugpy                 1.8.20
decorator               5.2.1
exceptiongroup          1.3.1
executing               2.2.1
flatbuffers             25.12.19
fonttools               4.60.2
gast                    0.7.0
google-pasta            0.2.0
grpcio                  1.78.0
h5py                    3.14.0
idna                    3.11
importlib-metadata      8.7.1
importlib-resources     6.5.2
ipykernel               6.31.0
ipython                 8.18.1
jedi                    0.19.2
joblib                  1.5.3
jupyter-client          8.6.3
jupyter-core            5.8.1
keras                   3.10.0
kiwisolver              1.4.7
libclang                18.1.1
markdown                3.9
markdown-it-py          3.0.0
markupsafe              3.0.3
matplotlib              3.9.4
matplotlib-inline       0.2.1
mdurl                   0.1.2
ml-dtypes               0.5.4
namex                   0.1.0
nest-asyncio            1.6.0
numpy                   2.0.2
opt-einsum              3.4.0
optree                  0.19.0
packaging               26.0
pandas                  2.3.3
parso                   0.8.6
pillow                  11.3.0
pip                     20.2.3
platformdirs            4.4.0
prompt-toolkit          3.0.52
protobuf                6.33.5
psutil                  7.2.2
pure-eval               0.2.3
pygments                2.19.2
pyparsing               3.3.2
python-dateutil         2.9.0.post0
pytz                    2025.2
pywin32                 311
pyzmq                   27.1.0
requests                2.32.5
rich                    14.3.3
scikit-learn            1.6.1
scipy                   1.13.1
setuptools              49.2.1
six                     1.17.0
stack-data              0.6.3
tensorboard             2.20.0
tensorboard-data-server 0.7.2
termcolor               3.1.0
threadpoolctl           3.6.0
tornado                 6.5.4
traitlets               5.14.3
typing-extensions       4.15.0
tzdata                  2025.3
urllib3                 2.6.3
wcwidth                 0.6.0
werkzeug                3.1.6
wheel                   0.46.3
wrapt                   2.1.1
zipp                    3.23.0
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 20.2.3; however, version 26.0.1 is available.
You should consider upgrading via the 'd:\AI-MLTraining\machine_learning\venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [19]:
import tensorflow

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
pip list

In [ ]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(3,activation='sigmoid',input_dim = 11))
model.add(Dense(1,activation='sigmoid'))

In [ ]:
model.summary()